#define WS2812_DI_PIN GP23
#define RGBLIGHT_LED_COUNT 2
#define RGBLED_SPLIT { 1, 1 }

#define RGBLIGHT_LAYERS
#define RGBLIGHT_LAYERS_RETAIN_VAL

#define LED_CAPS_LOCK_PIN GP25
#define SPLIT_LED_STATE_ENABLE
